Vagrant.configure("2") do |config|
	is_arm = RUBY_PLATFORM.include?("arm64") || RUBY_PLATFORM.include?("aarch64")
	config.vm.define "frontend" do |frontend|
		frontend.vm.box = "bento/ubuntu-22.04" if is_arm
		frontend.vm.box = "ubuntu/focal64" if !is_arm
		frontend.vm.box_architecture = "arm64" if is_arm
		frontend.vm.hostname = "frontend"
		frontend.vm.network "forwarded_port", guest: 80, host: 8080
		frontend.vm.network "forwarded_port", guest: 5173, host: "5173"
		frontend.vm.network "private_network", ip: "10.1.1.10",netmask: "255.255.255.0", virtualbox__intnet: "front_back"
		    frontend.vm.synced_folder "../shared/frontend", "/home/vagrant/frontend-source"

    frontend.vm.provider "virtualbox" do |vb|
        vb.gui = false
        vb.memory = "2048"
        vb.cpus = 2
        vb.name = "frontend"
    end

    frontend.vm.provision "shell", inline: <<-SHELL
        set -e

        sudo apt-get update

        sudo apt-get install -y \
            curl \
            net-tools \
            git \
            rsync

        curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
        sudo apt-get install -y nodejs

        echo "Node:"
        node -v

        echo "NPM:"
        npm -v

        sudo rm -rf /home/vagrant/frontend
        sudo mkdir -p /home/vagrant/frontend

        sudo rsync -a --exclude node_modules \
            /home/vagrant/frontend-source/ \
            /home/vagrant/frontend/

        sudo chown -R vagrant:vagrant /home/vagrant/frontend

        cd /home/vagrant/frontend

        # Instala dependências no filesystem Linux
        npm install

        cat <<'EOF' | sudo tee /etc/systemd/system/frontend.service
[Unit]
Description=React Frontend
After=network.target

[Service]
User=vagrant
WorkingDirectory=/home/vagrant/frontend
ExecStart=/usr/bin/npm run dev -- --host 0.0.0.0
Restart=always
Environment=NODE_ENV=development

[Install]
WantedBy=multi-user.target
EOF

        sudo systemctl daemon-reload
        sudo systemctl enable frontend
        sudo systemctl restart frontend

    SHELL

end

	config.vm.define "backend" do |backend|
		backend.vm.box = "bento/ubuntu-22.04" if is_arm
		backend.vm.box = "ubuntu/focal64" if !is_arm
		backend.vm.box_architecture = "arm64" if is_arm
		backend.vm.hostname = "backend"
		#backend.vm.network "forwarded_port", guest: 22, host: "2233"
		backend.vm.network "private_network", ip: "10.1.1.2",netmask: "255.255.255.0", virtualbox__intnet: "front_back"
		backend.vm.network "private_network", ip: "10.1.2.10",netmask: "255.255.255.0", virtualbox__intnet: "back_db"
		backend.vm.synced_folder "../shared/backend", "/home/vagrant/backend"
		backend.vm.provider "virtualbox" do |vb|
			vb.gui = false
			vb.memory = "2048"
			vb.cpus = 2
			vb.name = "backend"
			end
		backend.vm.provision "shell", inline: <<-SHELL
			set -e

			sudo apt-get update

			sudo apt-get install -y \
				curl \
				net-tools \
				git

			curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
			sudo apt-get install -y nodejs

			echo "Node:" 
			node -v 
			
			echo "NPM:" 
			npm -v

			cd /home/vagrant/backend

			npm install

			cat <<'EOF' | sudo tee /etc/systemd/system/backend.service
[Unit]
Description=Node.js Backend
After=network.target

[Service]
User=vagrant
WorkingDirectory=/home/vagrant/backend
ExecStart=/usr/bin/npm start
Restart=always
Environment=NODE_ENV=development

[Install]
WantedBy=multi-user.target
EOF

			sudo systemctl daemon-reload
			sudo systemctl enable backend
			sudo systemctl restart backend
		SHELL
	end

	config.vm.define "db" do |db|
		db.vm.box = "bento/ubuntu-22.04" if is_arm
		db.vm.box = "ubuntu/focal64" if !is_arm
		db.vm.box_architecture = "arm64" if is_arm
		db.vm.hostname = "db"
		db.vm.network "private_network", ip: "10.1.2.2",netmask: "255.255.255.0", virtualbox__intnet: "back_db"
		db.vm.synced_folder "../shared/db", "/home/vagrant/db"
		db.vm.provider "virtualbox" do  |vb|
			vb.gui = false
			vb.memory = "2048"
			vb.cpus = 2
			vb.name = "db"
			end
		db.vm.provision "shell", inline: <<-SHELL
			set -e

			sudo apt-get update

			sudo apt-get install -y \
				mysql-server \
				net-tools

			sudo systemctl enable mysql
			sudo systemctl start mysql

			sudo sed -i 's/^bind-address.*/bind-address = 10.1.2.2/' \
				/etc/mysql/mysql.conf.d/mysqld.cnf

			sudo systemctl restart mysql

			echo "Aguardando MySQL..."

			until sudo mysqladmin ping --silent; do 
				sleep 2
			done

			echo "MySQL está funcionando!"

			if [ -f /home/vagrant/db/schema.sql ]; then 
				echo "Executando schema.sql..." 
				sudo mysql < /home/vagrant/db/schema.sql 
				echo "schema.sql executado!" 
			else 
				echo "AVISO: schema.sql não encontrado!"
			fi

			echo "Bancos existentes:"

			sudo mysql -e "SHOW DATABASES;"

			echo "Database configurado!"

		SHELL
	end
end
